"""
Metadata mô tả các test case – dùng chung cho web_ui.py và helpers.py
"""
from config import ODOO_USER, ODOO_PASS

_PRE_LOGIN   = "Trình duyệt Chrome đã mở.\nURL Odoo Online có thể truy cập."
_PRE_PRODUCT = "Đã đăng nhập Odoo. Module Sales/Inventory đã cài đặt."

SUITE_META = {
    "login": {"label": "Suite 1.1 – Đăng nhập", "tcs": [
        {"id": "TC01", "desc": "Đăng nhập thành công với tài khoản hợp lệ",
         "precondition": _PRE_LOGIN,
         "steps": ["Truy cập URL Odoo Online", "Nhập email vào ô Login", "Nhập mật khẩu vào ô Password", "Nhấn nút Log in"],
         "data_input": f"Email: {ODOO_USER}\nPass: {ODOO_PASS}",
         "expected": "Đăng nhập thành công. URL chuyển sang /odoo. Dashboard hiển thị đầy đủ menu."},
        {"id": "TC02", "desc": "Đăng nhập thất bại – sai mật khẩu",
         "precondition": _PRE_LOGIN,
         "steps": ["Truy cập URL Odoo", "Nhập email hợp lệ", "Nhập sai mật khẩu", "Nhấn Log in"],
         "data_input": f"Email: {ODOO_USER}\nPass: wrong123",
         "expected": "Hiển thị thông báo lỗi: \"Wrong login/password\". Không chuyển sang trang dashboard."},
        {"id": "TC03", "desc": "Đăng nhập thất bại – để trống email",
         "precondition": _PRE_LOGIN,
         "steps": ["Truy cập URL Odoo", "Để trống ô Login (email)", "Nhập mật khẩu hợp lệ", "Nhấn Log in"],
         "data_input": f"Email: (trống)\nPass: {ODOO_PASS}",
         "expected": "Form báo lỗi trường bắt buộc. Không thực hiện đăng nhập."},
        {"id": "TC04", "desc": "Đăng nhập thất bại – để trống mật khẩu",
         "precondition": _PRE_LOGIN,
         "steps": ["Truy cập URL Odoo", "Nhập email hợp lệ", "Để trống ô Password", "Nhấn Log in"],
         "data_input": f"Email: {ODOO_USER}\nPass: (trống)",
         "expected": "Form báo lỗi trường bắt buộc. Không thực hiện đăng nhập."},
        {"id": "TC05", "desc": "Đăng nhập thất bại – email sai định dạng",
         "precondition": _PRE_LOGIN,
         "steps": ["Truy cập URL Odoo", "Nhập email sai định dạng", "Nhập mật khẩu hợp lệ", "Nhấn Log in"],
         "data_input": f"Email: adminabc\nPass: {ODOO_PASS}",
         "expected": "Hiển thị lỗi email không hợp lệ hoặc thông báo Wrong login/password."},
    ]},
    "logout": {"label": "Suite 1.2 – Đăng xuất", "tcs": [
        {"id": "TC06", "desc": "Đăng xuất thành công",
         "precondition": "Đã đăng nhập Odoo thành công bằng tài khoản admin.",
         "steps": ["Click vào avatar / tên người dùng góc trên phải", "Chọn Log out trong menu dropdown"],
         "data_input": "",
         "expected": "Đăng xuất thành công. URL chuyển về trang /web/login. Dashboard không còn hiển thị."},
        {"id": "TC07", "desc": "Kiểm tra session bị hủy sau khi đăng xuất",
         "precondition": "Người dùng đã logout khỏi hệ thống.",
         "steps": ["Sau khi logout, copy URL của màn hình trước đó", "Paste URL vào trình duyệt", "Nhấn Enter"],
         "data_input": "",
         "expected": "Hệ thống yêu cầu đăng nhập lại. Không truy cập được màn hình nội bộ."},
        {"id": "TC08", "desc": "Back button sau logout không vào lại được",
         "precondition": "Người dùng vừa logout thành công.",
         "steps": ["Nhấn nút Back trên trình duyệt"],
         "data_input": "",
         "expected": "Hệ thống không hiển thị lại dữ liệu phiên cũ. Người dùng vẫn ở màn hình login hoặc bị yêu cầu đăng nhập lại."},
        {"id": "TC09", "desc": "Đăng nhập lại thành công sau logout",
         "precondition": "Người dùng đã logout thành công.",
         "steps": ["Nhập username", "Nhập password", "Nhấn Login"],
         "data_input": f"Username: {ODOO_USER}\nPassword: {ODOO_PASS}",
         "expected": "Đăng nhập thành công và vào trang chủ hệ thống."},
    ]},
    "product": {"label": "Suite 2.1 – Tạo sản phẩm mới", "tcs": [
        {"id": "TC10", "desc": "Tạo sản phẩm mới thành công",
         "precondition": _PRE_PRODUCT,
         "steps": ["Vào Sales > Products", "Nhấn New", "Nhập tên sản phẩm", "Nhập giá bán", "Nhấn Save"],
         "data_input": "Tên: SP_TEST_[timestamp]\nGiá: 10.000",
         "expected": "Sản phẩm lưu thành công. URL chứa ID bản ghi. Tên hiển thị trên breadcrumb."},
        {"id": "TC11", "desc": "Tạo sản phẩm – để trống tên",
         "precondition": _PRE_PRODUCT,
         "steps": ["Vào Sales > Products", "Nhấn New", "Để trống tên sản phẩm", "Nhập giá bán", "Nhấn Save"],
         "data_input": "Tên: (trống)\nGiá: 10.000",
         "expected": "Báo lỗi trường tên bắt buộc. Không lưu được sản phẩm."},
        {"id": "TC12", "desc": "Tạo sản phẩm – nhập giá bán hợp lệ",
         "precondition": _PRE_PRODUCT,
         "steps": ["Vào Sales > Products", "Nhấn New", "Nhập tên sản phẩm", "Nhập giá bán hợp lệ", "Nhấn Save"],
         "data_input": "Tên: SP_TEST_xxx\nGiá: 10.000",
         "expected": "Giá bán = 10.000 hiển thị chính xác trên form sản phẩm."},
        {"id": "TC13", "desc": "Tạo sản phẩm – nhập giá bằng 0",
         "precondition": _PRE_PRODUCT,
         "steps": ["Vào Sales > Products", "Nhấn New", "Nhập tên sản phẩm", "Nhập giá = 0", "Nhấn Save"],
         "data_input": "Tên: SP_TEST_FREE\nGiá: 0",
         "expected": "Lưu thành công hoặc hiển thị cảnh báo theo rule hệ thống."},
        {"id": "TC14", "desc": "Tạo sản phẩm – nhập ký tự đặc biệt vào tên",
         "precondition": _PRE_PRODUCT,
         "steps": ["Vào Sales > Products", "Nhấn New", "Nhập tên có ký tự đặc biệt", "Nhập giá bán", "Nhấn Save"],
         "data_input": "Tên: SP_@#$%\nGiá: 10.000",
         "expected": "Xử lý đúng dữ liệu. Không lỗi giao diện hoặc encoding."},
        {"id": "TC15", "desc": "Tạo sản phẩm – nhập tên trùng",
         "precondition": _PRE_PRODUCT + "\nSản phẩm SP_TEST_DUPLICATE đã tồn tại.",
         "steps": ["Vào Sales > Products", "Nhấn New", "Nhập lại tên đã tồn tại", "Nhập giá bán", "Nhấn Save"],
         "data_input": "Tên: SP_TEST_DUPLICATE\nGiá: 10.000",
         "expected": "Hệ thống cho phép lưu hoặc hiển thị cảnh báo trùng tên."},
        {"id": "TC16", "desc": "Kiểm tra refresh sau khi lưu",
         "precondition": _PRE_PRODUCT,
         "steps": ["Tạo sản phẩm và nhấn Save", "Nhấn F5 hoặc refresh trình duyệt"],
         "data_input": "Tên: SP_REFRESH\nGiá: 10.000",
         "expected": "Dữ liệu sản phẩm vẫn lưu đúng sau refresh. Không mất record."},
        {"id": "TC17", "desc": "Kiểm tra tìm kiếm sản phẩm sau khi tạo",
         "precondition": _PRE_PRODUCT,
         "steps": ["Tạo sản phẩm và nhấn Save", "Quay lại danh sách Products", "Nhập tên sản phẩm vào ô Search", "Nhấn Enter"],
         "data_input": "Tên tìm: SP_SEARCH\nGiá: 10.000",
         "expected": "Hiển thị đúng sản phẩm vừa tạo trong danh sách kết quả."},
    ]},
    "inventory": {"label": "Suite 2.2 – Cập nhật số lượng tồn kho", "tcs": [
        {"id": "TC18", "desc": "Cập nhật số lượng tồn kho thành công",
         "precondition": "Đã đăng nhập Odoo. Module Inventory đã cài đặt.\nSản phẩm SP_TEST_xxx đã được tạo.",
         "steps": ["Mở form chi tiết sản phẩm SP_TEST_xxx", "Nhấn Update Quantity", "Nhấn New", "Nhập số lượng vào ô Quantity", "Nhấn Apply All", "Xác nhận"],
         "data_input": "Số lượng: 50",
         "expected": "Tồn kho cập nhật thành công. On Hand hiển thị = 50."},
        {"id": "TC19", "desc": "Tìm kiếm sản phẩm đã tạo",
         "precondition": "Đã đăng nhập Odoo.\nSản phẩm SP_TEST_xxx đã tồn tại trong hệ thống.",
         "steps": ["Vào Sales > Products", "Nhập tên sản phẩm vào ô Search", "Nhấn Enter"],
         "data_input": "Tên tìm: SP_TEST_xxx",
         "expected": "Kết quả hiển thị đúng sản phẩm. Tên và giá hiển thị chính xác."},
    ]},
    "purchase": {"label": "Suite 3.1 – Đơn mua hàng (Purchase Order)", "tcs": [
        {"id": "TC20", "desc": "Tạo đơn mua hàng và xác nhận thành công",
         "precondition": "Đã đăng nhập Odoo. Module Purchase đã cài đặt.\nSP_TEST_xxx tồn kho = 50.",
         "steps": ["Vào menu Purchase", "Nhấn New", "Chọn Vendor (NCC đầu tiên)", "Nhấn Add a product", "Tìm và chọn SP_TEST_xxx", "Nhập số lượng", "Nhấn Confirm Order"],
         "data_input": "NCC: đầu tiên trong hệ thống\nSản phẩm: SP_TEST_xxx\nSL: 2",
         "expected": "Xác nhận thành công. Status Bar hiển thị Purchase Order. Nút Receive Products xuất hiện."},
        {"id": "TC21", "desc": "Tạo đơn mua – không chọn nhà cung cấp",
         "precondition": "Đã đăng nhập Odoo. Module Purchase đã cài đặt.\nSP_TEST_xxx tồn kho = 50.",
         "steps": ["Vào menu Purchase", "Nhấn New", "Để trống Vendor", "Thêm sản phẩm SP_TEST_xxx", "Nhập số lượng", "Nhấn Confirm Order"],
         "data_input": "NCC: (trống)\nSản phẩm: SP_TEST_xxx\nSL: 2",
         "expected": "Báo lỗi thiếu nhà cung cấp. Không xác nhận được đơn hàng."},
        {"id": "TC22", "desc": "Nhập kho thành công sau khi xác nhận PO",
         "precondition": "Đã đăng nhập Odoo. Module Purchase đã cài đặt.\nPO đang ở trạng thái Purchase Order.",
         "steps": ["Từ form PO đã xác nhận", "Nhấn Receive Products", "Kiểm tra số lượng nhận", "Nhấn Validate", "Xử lý popup nếu có"],
         "data_input": "SL nhận: 2",
         "expected": "Receipt chuyển trạng thái Done. Tồn kho SP_TEST_xxx tăng = 52."},
        {"id": "TC23", "desc": "Kiểm tra trạng thái PO sau khi xác nhận",
         "precondition": "Đã đăng nhập Odoo. Module Purchase đã cài đặt.\nSP_TEST_xxx tồn kho = 50.",
         "steps": ["Tạo đơn mua hàng đầy đủ thông tin", "Nhấn Confirm Order", "Quan sát Status Bar trên form"],
         "data_input": "",
         "expected": "Status Bar hiển thị Purchase Order. Nút Receive Products xuất hiện."},
        {"id": "TC24", "desc": "Kiểm tra tồn kho tăng sau khi nhập kho",
         "precondition": "Đã đăng nhập Odoo. Module Purchase đã cài đặt.\nPhiếu nhập kho đã được Validate.",
         "steps": ["Vào Inventory > Products", "Tìm kiếm SP_TEST_xxx", "Kiểm tra giá trị On Hand"],
         "data_input": "Tồn trước: 50\nSL nhập: 2",
         "expected": "On Hand = 52. Tồn kho tăng đúng số lượng đã nhập."},
    ]},
    "sales": {"label": "Suite 3.2 – Đơn bán hàng (Sales Order)", "tcs": [
        {"id": "TC25", "desc": "Tạo Sales Order mới",
         "precondition": "Đã đăng nhập Odoo. Module Sales đã cài đặt.",
         "steps": ["Vào menu Sales", "Nhấn New"],
         "data_input": "",
         "expected": "Form tạo Sales Order mở thành công."},
        {"id": "TC26", "desc": "Chọn khách hàng cho Sales Order",
         "precondition": "Đang ở form tạo Sales Order mới.",
         "steps": ["Click vào ô Customer", "Chọn khách hàng đầu tiên trong danh sách"],
         "data_input": "KH: đầu tiên trong hệ thống",
         "expected": "Khách hàng hiển thị đúng trên đơn bán hàng."},
        {"id": "TC27", "desc": "Thêm sản phẩm vào Sales Order",
         "precondition": "SP_TEST_xxx có tồn kho ≥ 2.\nĐang ở form SO đã có khách hàng.",
         "steps": ["Nhấn Add a product trong tab Order Lines", "Tìm kiếm SP_TEST_xxx", "Chọn sản phẩm"],
         "data_input": "Sản phẩm: SP_TEST_xxx",
         "expected": "Sản phẩm SP_TEST_xxx được thêm vào dòng đơn hàng."},
        {"id": "TC28", "desc": "Nhập số lượng sản phẩm trong SO",
         "precondition": "Sản phẩm SP_TEST_xxx đã được thêm vào dòng đơn hàng.",
         "steps": ["Nhập số lượng vào ô Quantity", "Nhấn Tab"],
         "data_input": "SL: 2",
         "expected": "Số lượng cập nhật thành công trên dòng đơn hàng."},
        {"id": "TC29", "desc": "Confirm SO khi thiếu khách hàng",
         "precondition": "Đang ở form tạo Sales Order mới, chưa chọn khách hàng.",
         "steps": ["Để trống ô Customer", "Thêm sản phẩm SP_TEST_xxx", "Nhập số lượng", "Nhấn Confirm"],
         "data_input": "KH: (trống)\nSản phẩm: SP_TEST_xxx\nSL: 2",
         "expected": "Báo lỗi thiếu khách hàng. Không xác nhận được đơn hàng."},
        {"id": "TC30", "desc": "Confirm Sales Order thành công",
         "precondition": "SO đã có đầy đủ khách hàng và sản phẩm hợp lệ.",
         "steps": ["Kiểm tra thông tin đơn hàng", "Nhấn Confirm"],
         "data_input": "",
         "expected": "SO xác nhận thành công. Status Bar hiển thị Sales Order. Badge Delivery xuất hiện với SL = 1."},
        {"id": "TC31", "desc": "Mở phiếu Delivery từ SO",
         "precondition": "SO đang ở trạng thái Sales Order.",
         "steps": ["Nhấn vào badge Delivery trên form SO"],
         "data_input": "",
         "expected": "Màn hình Delivery Order mở thành công."},
        {"id": "TC32", "desc": "Kiểm tra số lượng cần giao trong Delivery",
         "precondition": "Đang ở form Delivery Order.",
         "steps": ["Kiểm tra cột Demand Quantity trong tab Operations"],
         "data_input": "SL đặt: 2",
         "expected": "Số lượng Demand bằng đúng số lượng đã đặt trong SO."},
        {"id": "TC33", "desc": "Validate Delivery thành công",
         "precondition": "Delivery Order đang ở trạng thái Ready.",
         "steps": ["Kiểm tra số lượng Done", "Nhấn Validate", "Xử lý popup nếu có"],
         "data_input": "SL xuất: 2",
         "expected": "Delivery chuyển trạng thái Done. Tồn kho giảm đúng."},
        {"id": "TC34", "desc": "Kiểm tra tồn kho giảm sau khi xuất kho",
         "precondition": "Delivery Order đã được Validate thành công.\nTồn kho SP_TEST_xxx trước xuất = 52.",
         "steps": ["Vào Inventory > Products", "Tìm kiếm SP_TEST_xxx", "Kiểm tra giá trị On Hand"],
         "data_input": "Tồn trước: 52\nSL xuất: 2",
         "expected": "On Hand = 50. Tồn kho giảm đúng số lượng đã xuất."},
    ]},
}

# Flat lookup: TC01 → {id, desc, precondition, steps, data_input, expected, suite_label}
TC_META = {
    tc["id"]: {**tc, "suite_label": suite["label"]}
    for suite in SUITE_META.values()
    for tc in suite["tcs"]
}
